### ISSUE TITLE
[Audience] Retrieval of large sized audience too slow

### ISSUE THREAD

**Issue by paagla123** [coa0329/BhaangWeb#116]
Under Account MindFire Master, Mackenzi's Prospect list last over 44,000 contacts - takes a long time to retrieve.  We need to discuss how to approach this - I suggest we paginate the retrieval and display how Ton did it for Salem CRM.

**Comment by daver78** [comment]
@paagla123 Where are you talking about?  

Do you mean getting the count takes a long time, or displaying the list of actual Contacts?

If it's the actual Contacts, this is why I asked if we were pulling from DW instead of OD.  I believe with DW we can paginate, but OD we do not.  I could be wrong, however.

**Comment by paagla123** [comment]
@daver78 getting count is fast. Displaying the list is slow, and for 40,000+ I assume it times out, because nothing shows up

**Comment by daver78** [comment]
@paagla123 I don't think the REST times out, but I seem to recall there is a `datatables` optimization for this.  @coa0329 may know, or can look into it.  

That said, pagination would be better.  Do you recall if we paginate responses from DW?

**Comment by coa0329** [comment]
I use GetContactList api. Where does it get data from DW or OD ?

=====

I get this error "ERR_EMPTY_RESPONSE" from getContact.php. It may be time out. I will increase it.

**Comment by daver78** [comment]
@coa0329 Ahh, it could be the `php` timeout.  if the endpoint is something like `/REST/getContactList` then that's OD, not DW.

**Comment by paagla123** [comment]
@coa0329 @jiewsone pl look at how it was done in SalemCRM 
https://keiger.com-ext.com/salem_crm/Portal.php

**Comment by coa0329** [comment]
@paagla123 

Fixed on stage.
We can get the contacts of that audience now.

![190](https://user-images.githubusercontent.com/7914690/31376864-78e083d4-add0-11e7-86c9-116cc8511423.JPG)

=============

showContact.php was killed by oom-killer.

![189](https://user-images.githubusercontent.com/7914690/31376670-e7e486e6-adcf-11e7-9397-73ec063e8d51.JPG)

=============

Kwang found that we don't have Swap on the server. So he create it.

![188](https://user-images.githubusercontent.com/7914690/31376562-94e2d560-adcf-11e7-9449-ed4ccec2a2c0.JPG)

=============

Then he notice that we have only 1GB of memory and 30 GB of space on the server.

![187](https://user-images.githubusercontent.com/7914690/31376589-ab2eb438-adcf-11e7-96c8-dc7861d34ce4.JPG)

=============

Should we have more memory and space on it ?

**Comment by paagla123** [comment]
@coa0329 this e still not working for me.

Re server, 1GB / 30GB seems  low. Pl talk to Chay and see if we can upgrade. Thx

**Comment by coa0329** [comment]
@paagla123 I cannot repeat it. I get data every time.

--------------

Server : See the price at https://www.digitalocean.com/pricing/#droplet, which one do you want ?
We use $10 / mo now.

**Comment by paagla123** [comment]
Let's go to the next level $20

**Comment by daver78** [comment]
@paagla123 Is there a reason we don't put DV at AWS?  

I don't know much about Digital Ocean ... but I think that once we launch, we may want to have a load balancer (ELB) in front of DV, not to mention WAF, VPC, and other things to protect ourselves & Users.

I assume DO has something like this, but it may be better to consolidate @ AWS since we have lots of organizational knowledge about their services/products.

Thoughts?

**Comment by paagla123** [comment]
@daver78 yes. We need to take that up as a project as some point before we go to production.

**Comment by paagla123** [comment]
@coa0329 @paweenwich - i GOT THIS error in teh Colsole when I ran a "See All my Contacts" (about 8,000 contacts) on the sub acct Solution21. Hope this will point you tothe right din
![image](https://user-images.githubusercontent.com/29718335/31629668-2cb06b9e-b269-11e7-9171-0965eeec5f52.png)

**Comment by AumpaiFung** [comment]
@paagla123    Stage fixed. 

When we open showContact.php page, the count people number on header will refresh from the real data on that time. 
(See Pic1 below)
![1](https://user-images.githubusercontent.com/30495097/31712528-90ba333c-b425-11e7-887f-558a21bfa865.jpg)

Question: 
1. Should we update count value in couchDB?
2. If answer is Yes, Do you want to update modified date or not?
![2](https://user-images.githubusercontent.com/30495097/31712606-ca5c42d8-b425-11e7-981c-dfe150eca891.jpg)

**Comment by paagla123** [comment]
@AumpaiFung yes to both please. Thank you

**Comment by paagla123** [comment]
@AumpaiFung you have to paginate. Mackenzi's Prospect List in MindFire Master with 44,210 records took approx 48 seconds - that is not acceptable. The requirements are, the first page of data must show up within 5 seconds. Check out https://keiger.com-ext.com/salem_crm/Search.php and  https://keiger.com-ext.com/salem_crm/Result.php

**Comment by daver78** [comment]
@paagla123 Can you send me the login creds for this?  I wanna see this holy pagination.

**Comment by paagla123** [comment]
Actually its in a function called loadcontactsbyPage in Share.php in the folder: 
/var/www/vhosts/keiger.com-ext.com/httpdocs/salem_crm
Log in with root

**Comment by AumpaiFung** [comment]
@paagla123   I fixed about console error.

**Comment by daver78** [comment]
@paagla123 and @coa0329: I read your chat last night.  Few items:

1- @coa0329 I don't understand what Bootstrap has to do with @paagla123's request that we obtain 1k records at a time from the DB.  I believe that `datatables` (or `footables` -- I can't recall which you used) has a feature for async request of data for each page.  Have you looked at this?

2- @coa0329 I also don't understand why you need to "control every button" in order to do what @paagla123 is asking.  What do you mean?

3- @paagla123 I agree (101%!) that this needs to load quickly for the User.  However, have you thought deeply about your pagination request?  

For example, what should happen when I sort A->Z or "Search"/"Filter" for a record?  As a User, I would expect it to look through the entire list ... but if I understand your request correctly, it will only look through what's been loaded so far?

This is why I think you should consider using the DW instead of the OD.  We had to tackle and solve the same problem in Studio Reporting already, and if I'm not mistaken, we used the DW.  You can find out by looking at the code or asking JV, BT, AA, etc.

**Comment by coa0329** [comment]
@paagla123 @daver78 

**For example, what should happen when I sort A->Z or "Search"/"Filter" for a record? As a User, I would expect it to look through the entire list ... but if I understand your request correctly, it will only look through what's been loaded so far?**

This is what I try to say. If we don't write the code to control the bootstrap, the next, prev, goto page and every buttons will be like that too. 

=========

We can try DW, if you can provide us the api to get data.

**Comment by paweenwich** [comment]
@daver78 @paagla123 

To handle huge data we need server side pagination.  Basically, we need the API for 
- retrieve data in page 
- search in subset 
- sort data 
I think we can use contactservice/GetContactsByPage to do all above.  However, I need document/example of how to use 

<SortExpression>String content</SortExpression>

For example, to sort "FirstName ASC, LastName DSC", What I need to put in SortExpression?

**Comment by daver78** [comment]
@paagla123 I'm confused by last night's chat.  I thought where you and left this is **we may not need to change anything in our code, merely have @amalekshahi apply an index**.  Our thought was that at least for now, this could solve our problem(s) and allow us to move forward.

What happened to that?  Did you speak to Ali about that, or did you forget? :)

**Comment by paagla123** [comment]
@daver78 I don;t know what field we are indexing by
@paweenwich did you see teh code in keiger.com-ext.com/crm-salem?

**Comment by daver78** [comment]
@paagla123 You can figure that out with @amalekshahi -- no?

**Comment by paagla123** [comment]
@daver78 I'll ask him - but @paweenwich shoul look at what was done for Sales - it worked for 73000 records, not huge data. We don;t anticipate more than 100K for now

**Comment by paagla123** [comment]
@javpowell team is using contactservice/GetContactsByPage . However, we need help with document/example of how to use
<SortExpression>String content</SortExpression>

For example, to sort "FirstName ASC, LastName DSC", What I need to put in SortExpression?

**Comment by paweenwich** [comment]
@paagla123 Done,  For contact set < 10000, we do previous memory mode.  (Load everything in memory and do search/sort/page in memory).   For contact > 10000, we switch to server mode.  Right now only paging and searching work.  Sort need server side API.

**Comment by paagla123** [comment]
@paweenwich ok thank you great work

**Comment by javpowell** [comment]
@paagla123 I will ask Amir today about how the Sort works.

**Comment by javpowell** [comment]
@paagla123 For sort expression you can do 3 things. 

1) "FieldName" - this will sort Ascending by default on the selected fieldname
2) "FieldName ASC" or "FieldName DESC" - this will sort Ascending or Descending on the selected fieldname
3) "FieldName,FieldName ASC" or "FieldName,FieldName DESC" - this will sort Ascending or Descending on the selected fieldnames

**Comment by paagla123** [comment]
@paweenwich pl see answers to your questions here. Thx

**Comment by paweenwich** [comment]
@paagla123 Done, sort is supported

**Comment by paagla123** [comment]
@paweenwich @daver78 @javpowell Thanks to all of you. I will test today and close if no issues.
This does not seem that critical, but can be really problem-some from user experience point of view.

**Comment by paagla123** [comment]
Closing. Thanks
